crudBundle/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace crudBundle.Controllers
{
    [Route("[controller]")]

    public class CountriesController : Controller
    {
        private readonly ICountriesService _countriesService;
        public CountriesController(ICountriesService countriesService)
        {
            _countriesService= countriesService;
        }

        [Route("[action]")]
        public IActionResult UploadFromExcel()
        {
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
        {
            if(excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file";
                return View();
            }
            if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported file. 'Please select an '.xlsx' file";
                return View();
            }

            int countriesCountInserted = await _countriesService.UploadCountriesFromExcelFile(excelFile);

            ViewBag.Message = $"{countriesCountInserted} Countries Uploaded ";
            return View();
        }
    }
}

crudBundle/Views/Countries/UploadFromExcel.cshtml
@{
    ViewBag.Title = "Upload Countries from Excel";
}

<div class="flex">
    <div class="flex-1">
        <div class="text-grey">
            <span>Contacts</span>
            <i class="fa-solid fa-caret-right"></i>
            <span class="text-grey">Persons</span>
            <i class="fa-solid fa-caret-right"></i>
            <span class="text-grey">Upload</span>
        </div>
    </div>
</div>


<div class="form-container">
    <h2 class="text-large">Upload Countries from Excel</h2>
    <form asp-action="UploadFromExcel" asp-controller="Countries" method="post" enctype="multipart/form-data">
        @*mulitpart/from-data supports uploading files*@

        @*ExcelFile*@
        <div class="form-field fles">
            <div class="w-50">
                <label class="form-label pt">Choose an xlsx file</label>
                <input type="file" name="excelFile" class="form-input" />
                <div class="text-red">@ViewBag.ErrorMessage</div>
                <div class="text-green">@ViewBag.Message</div>
            </div>
        </div>

        <div class="form-field flex">
        <div class="w-25"></div>
        <div class="flex-1">
            <button type="submit" class="button button-green-back">Upload</button>
        </div>
        </div>
    </form>
</div>